export_i18n_js: true
js_file_path: "app/javascript/custom/translations.js"
translations:
  - file: "app/javascript/custom/translations.js"
    patterns:
      - "javascript.*"
      - "errors.*"
      - "admin.categories.javascript.*"
      - "checkout.*"
